image: {}
loaderImage: 
  # Github repo: https://github.com/magda-io/magda-configmap-dir-loader
  repository: docker.io/data61
  tag: 0.0.57-0
  pullPolicy: IfNotPresent
  imagePullSecret: false
autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
replicas: 1
resources:
  requests:
    cpu: 20m
    memory: 50Mi
  limits:
    cpu: 100m
# customPolicyConfigMaps -- a list of names of the configMaps that contains custom policy files.
# the configMap must be created using magda helm chart template: [magda.filesToJson](https://github.com/magda-io/magda/blob/21499b75c7a7ee00d68886338713217d83ccb91f/deploy/helm/magda-core/templates/_helpers.tpl#L244).
# More info see [here](https://github.com/magda-io/magda-configmap-dir-loader).
customPolicyConfigMaps: []