image: {}
elasticsearch:
  shards: 1
  replicas: 0
  useGcsSnapshots: false
resources:
  requests:
    cpu: 1000m
    memory: 250Mi
  limits:
    cpu: 2000m
    memory: 4Gi
makeSnapshots: false
readSnapshots: false
