{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    {{- if .Values.serviceAccount.annotations }}
    annotations:
      {{-  range $key, $value := .Values.serviceAccount.annotations }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
    {{- end }}
    name: {{ .Values.serviceAccount.name | default "magda-admin-api-service-account" }}
    {{ printf "\n" }}
{{- end }}
